#!/usr/bin/env bash

# Updates the local machine

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../../..

echo "=== SYSTEM UPDATE ====================================="
sudo apt-get update
sudo apt-get upgrade -y -q
echo "DONE."
