#!/usr/bin/env ruby

require './config/environment'

team = Team.find_by_acronym("BAMRU")

group_opts = [
  {
    name: "Ranks", acronym: "RA"
  },
  {
    name: "Roles", acronym: "RO"
  },
  {
    name: "Deployable", acronym: "DE"
  },
  {
    name: "Base", acronym: "BA"
  },
  {
    name: "Submittable", acronym: "SUB"
  },
  {
    name: "Sworn", acronym: "SWORN"
  }
].map {|el| el.merge({team: team})}

Cert::group.create group_opts

unit_role_opts = [
  {
    name: "Unit Leader", acronym: "UL"
  },
  {
    name: "Operations Officer", acronym: "OO"
  },
  {
    name: "Executive Officer", acronym: "XO"
  },
  {
    name: "asdf3"
  },
  {
    name: "asdf5"
  },
  {
    name: "asdf6"
  }
].merge({team: team, cert_groups: [Cert::Group.by_acronym("RO")]})

Cert::Unit.create unit_role_opts

puts "CertGroups: " + Cert::Group.count
puts "CertUnits: "  + Cert::Unit.count
