#!/usr/bin/env ruby

require './config/environment'

Cert::Permission.destroy_all
Cert::Spec.destroy_all
Cert::Proof.destroy_all
Cert::Prooflink.destroy_all
Cert::Group.destroy_all
Cert::Grouplink.destroy_all

