#!/usr/bin/env ruby

require './config/environment'

team = Team.find_by_acronym("BAMRU")

group_opts = [
  {
    name: "Ranks", acronym: "RA"
  },
  {
    name: "Roles", acronym: "RO"
  },
  {
    name: "Deployable", acronym: "DE"
  },
  {
    name: "Base", acronym: "BA"
  },
  {
    name: "Submittable", acronym: "SUB"
  },
  {
    name: "Sworn", acronym: "SWORN"
  }
].map {|el| el.merge({team: team})}

Cert::Group.create group_opts

unit_role_opts = [
  {
    name: "Unit Leader", acronym: "UL"
  },
  {
    name: "Operations Officer", acronym: "OO"
  },
  {
    name: "Executive Officer", acronym: "XO"
  },
  {
    name: "Secretary", acronym: "S"
  },
  {
    name: "Treasurer", acronym: "T"
  },
  {
    name: "Training Officer", acronym: "TO"
  },
  {
    name: "Recruiting Officer", acronym: "RO"
  }
].map {|el| el.merge({team: team})}

Cert::Description.create unit_role_opts

unit_rank_opts = [
  {
    name: "Technical Member", acronym: "TM"
  },
  {
    name: "Field Member", acronym: "FM"
  },
  {
    name: "Trainee", acronym: "T"
  },
  {
    name: "Reserve", acronym: "R"
  },
  {
    name: "Support", acronym: "S"
  },
  {
    name: "Associate", acronym: "A"
  },
  {
    name: "Guest", acronym: "G"
  },
].map {|el| el.merge({team: team})}

Cert::Description.create unit_rank_opts

rank_group = Cert::Group.by_acronym("RA").all.first
role_group = Cert::Group.by_acronym("RO").all.first

unit_rank_opts.each do |el|
  desc = Cert::Description.where(name: el[:name]).all.first
  Cert::Grouptie.create(cert_group: rank_group, cert_description: desc)
end

unit_role_opts.each do |el|
  desc = Cert::Description.where(name: el[:name]).all.first
  Cert::Grouptie.create(cert_group: role_group, cert_description: desc)
end

puts "CertDescriptions: " + Cert::Description.count.to_s
puts "CertGroups:       " + Cert::Group.count.to_s
puts "CertGroupties:    " + Cert::Grouptie.count.to_s
