#!/usr/bin/env bash
# should be called from tmux_dashboard

export APP="xmguard"

create_new_session()
{

  cd /home/aleak/lr/ListCall

  tmux new-session -s $APP -n GUARD -d

  tmux send-keys -t $APP:1 'cls ; cd /home/aleak/lr/ListCall ; RUBYOPT=W0 bundle exec guard -c'  C-m

}

