common: &common
  pool: 5
  adapter:  postgresql
  encoding: UTF8
  template: template_base
  username: postgres
  password: postgres

development:
  <<: *common
  database: lica_development

test:
  <<: *common
  database: lica_test

staging:
 <<: *common
 database: lica_staging

production:
  <<: *common
  database: lica_production

travis:
  adapter:  postgresql
  username: postgres
  database: lica_travis
