# This file was generated by the `rails generate rspec:install` command.
# Conventionally, all specs live under a `spec` directory, which RSpec adds
# to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which causes this
# file to always be loaded, without a need to explicitly require it in any files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, make a
# separate helper file that requires this one and then use it only in the specs
# that actually need it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require_relative './spec_support.rb'

RSpec.configure do |config|

  config.deprecation_stream = '/tmp/rspec_deprecations.txt'
  # config.raise_errors_for_deprecations!

  config.register_ordering(:global) do |items|
    items.sort_by do |group|
      case group.metadata[:type]
      when :feature    then 50          # run feature specs last...
      when :request    then 40
      when :importer   then 35
      when :controller then 30
      when :mailer     then 15
      when :model      then 10          # models go first
      else 20
      end
    end
  end

  config.expect_with :rspec do |expectations|
    # Enable only the newer, non-monkey-patching expect syntax.
    # http://myronmars.to/n/dev-blog/2012/06/rspecs-new-expectation-syntax
    expectations.syntax = :expect
  end

  config.mock_with :rspec do |mocks|
    # Enable only the newer, non-monkey-patching expect syntax.
    # http://teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
    mocks.syntax = :expect

    # Prevent mocking/stubbing a method that does not exist on a real object.
    mocks.verify_partial_doubles = true
  end

  # auto-generated tags
  config.define_derived_metadata(:file_path => %r{/spec/feature}) do |metadata|
    metadata[:feature] = true
  end
  config.define_derived_metadata(:file_path => %r{/spec/msgs}) do |metadata|
    metadata[:msgs] = true
  end
end
