---
# to run:
# - vagrant provision  
- vars:
    - rem_host:     all           
    - rem_user:     vagrant      
    # - rem_host:     lch1
    # - rem_user:     deploy
    # - roles_dir:    ~/.ansible/playbooks/roles       
    - lcl_user:     aleak                            
    - lcl_root:     "/home/{{lcl_user}}/lr/lica"
    - dotfile:      "{{lcl_root}}/.env"
    - pg_user:      "{{APP_NAME}}"
    - pg_pass:      "{{POSTGRES_PASS}}"
    - pg_dbs:
        - "{{pg_user}}_production"
        - "{{pg_user}}_test"
        - "{{pg_user}}_development"
  remote_user: "{{rem_user}}"
  hosts:       "{{rem_host}}"
  roles:
    - /dotdeb"
    - /cli_base"
    - /cli_user"
    - /cli_util"
    - /chruby"
    - /ruby-install"
    - /ruby_gems"
    - /postgres"
    - /postgres_user"
    - /postgres_db"  
    - /nginx"
    - /redis"
    - /memcached"

