#!/usr/bin/env bash

# download the seed data

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

echo "=== download data ========================================"
cd ~
mkdir -p var/seed/lica
cd var/seed/lica
wormhole receive
