#!/usr/bin/env bash

# get the database file (db/backup/data.psql)

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTDIR/../..

save_file() {
  timestamp=$(date +%y%m%d_%H%M%S)
  altfile=$1.$timestamp.save
  [ -f "$1" ] && echo "Saving $1 to $altfile" && mv $1 $altfile
}

echo "=== get .db ========================================"
mkdir -f db/backup
cd db/backup
save_file data.psql
wormhole receive
echo "Done."
