
class AdminOpts

  MENUS = {
      Lica_Team: {
          names:      { label: 'names',
                        title: "Team Names and URL's",
                        desc:  "Change team name, logo text, and URL's",
                        path:  '/admin/team_names',
                        icon:  'quote-left' },
          icon:       { label: 'icon',
                        title: 'Team Icon',
                        desc:  'Update the icon shown on the browser and team logo',
                        path:  '/admin/team_icon',
                        icon:  'picture-o' },
          owners:     { label: 'owner+',
                        title: 'Team Owner+',
                        desc:  'Assign owner+ rights',
                        path:  '/admin/team_owners',
                        icon:  'bank' },
          # features:   { label: "features",
          #               title: "Team Features",
          #               path:  "/admin/team_features",
          #               desc:  "Select the features that will be used by the team",
          #               icon:  "check" },
          navs:       { label: 'navigation',
                        title: 'Team Navigation',
                        desc:  'Update the header and footer navigation links',
                        path:  '/admin/team_navs',
                        icon:  'ellipsis-h' },
          partners:   { label: 'partners',
                        title: 'Team Partners',
                        desc:  'Create and remove team partnerships',
                        path:  '/admin/team_partners',
                        icon:  'cogs' },
      },
      Lica_Certs: {
        groups:      {  label: 'groups',
                        title: 'Cert Groups',
                         desc: 'Manage Cert Groups',
                         path: '/admin/cert_groups',
                         icon: 'group' },
        descriptions: { label: 'descriptions',
                        title: 'Cert Descriptions',
                         desc: 'Manage Cert Descriptions',
                         path: '/admin/cert_descriptions',
                         icon: 'check' },
      },
      Lica_Members: {
          ranks:      { label: 'ranks',
                        title: 'Member Ranks',
                        desc:  'Define member Ranks',
                        path:  '/admin/member_ranks',
                        icon:  'angle-double-up' },
          roles:      { label: 'roles',
                        title: 'Member Roles',
                        desc:  'Define member Roles',
                        path:  '/admin/member_roles',
                        icon:  'shield' },
          attributes: { label: 'attributes',
                        title: 'Member Attributes',
                        desc:  'Define team-specific Attributes for your Members',
                        path:  '/admin/member_attributes',
                        icon:  'list' },
          registry:   { label: 'registry',
                        title: 'Member Registry',
                        desc:  'Assign Ranks and Roles to your Members',
                        path:  '/admin/member_registry',
                        icon:  'group',
                        view:  'manager' },
          add:       {  label:  'add',
                        title: 'Add Member',
                        desc:  'Add new Member',
                        path:  '/admin/member_add',
                        icon:  'user-plus',
                        view:  'manager' },
          drop:       { label: 'drop',
                        title: 'Drop Member',
                        desc:  'Drop a Member',
                        path:  '/admin/member_drop',
                        icon:  'trash',
                        view:  'manager' },
      },
      Lica_Qualifications: {
        index:        { label: 'index',
                        title: 'Qualifications',
                        desc:  'Create/Update/Delete qualifications',
                        path:  '/admin/quals',
                        icon:  'database' },
        ctypes:        { label: 'types',
                         title: 'Certification Types',
                         desc:  'Create/Update/Delete cert types',
                         path:  '/admin/qual_ctypes',
                         icon:  'pencil-square-o' },
        assignments:  { label: 'assignments',
                        title: 'Qualification Assignments',
                        desc:  'Assign cert types to qualifications',
                        path:  '/admin/qual_assignments',
                        icon:  'check-square-o' },
        partners:     { label: "partners",
                        title: "Qualification Partners",
                        desc:  "Manage partner qualifications",
                        path:  "/admin/qual_partners",
                        icon:  "cogs" },
      },
      Lica_Events: {
        types:      { label: 'types',
                      title: 'Event Types',
                      desc:  'Define the Event Types for your Team',
                      path:  '/admin/event_types',
                      icon:  'table' },
        roles:      { label: 'roles',
                      title: 'Event Roles',
                      desc:  'Define the Event Roles for your Team',
                      path:  '/admin/event_roles',
                      icon:  'shield' },
        attributes: { label: "attributes",
                     title: "Event Attributes",
                     desc:  "Define team-specific Attributes for your Events",
                     path:  "/admin/event_attributes",
                     icon:  "list" },
      },
      Lica_Positions: {
        index:        { label: 'index',
                        title: 'Positions',
                        desc:  'Create/Update/Delete positions',
                        path:  '/admin/position_index',
                        icon:  'database' },
        partners:     { label: 'partners',
                        title: 'Position Partners',
                        desc:  'Manage partner positions',
                        path:  '/admin/position_partners',
                        icon:  'cogs' },
      },
  }

  def self.menus
    MENUS
  end

end
