
class AdminOpts

  MENUS = {
      Lica_Team: {
          names:      { label: 'names',
                        title: "Team Names and URL's",
                        desc:  "Change team name, logo text, and URL's",
                        path:  '/admin/team_names',
                        icon:  'quote-left' },
          icon:       { label: 'icon',
                        title: 'Team Icon',
                        desc:  'Update the icon shown on the browser and team logo',
                        path:  '/admin/team_icon',
                        icon:  'picture-o' },
          owners:     { label: 'owner+',
                        title: 'Team Owner+',
                        desc:  'Assign owner+ rights',
                        path:  '/admin/team_owners',
                        icon:  'bank' },
          # features:   { label: "features",
          #               title: "Team Features",
          #               path:  "/admin/team_features",
          #               desc:  "Select the features that will be used by the team",
          #               icon:  "check" },
          navs:       { label: 'navigation',
                        title: 'Team Navigation',
                        desc:  'Update the header and footer navigation links',
                        path:  '/admin/team_navs',
                        icon:  'ellipsis-h' },
          partners:   { label: 'partners',
                        title: 'Team Partners',
                        desc:  'Create and remove team partnerships',
                        path:  '/admin/team_partners',
                        icon:  'cogs' },
          # import:     { label: "import",
          #               title: "Data Import",
          #               desc:  "Import team data from CSV/XLS data files",
          #               path:  "/admin/data_import",
          #               icon:  "cloud-upload" },
          #               icon:  "cloud-upload" },
      },
      Lica_Members: {
          ranks:      { label: 'ranks',
                        title: 'Member Ranks',
                        desc:  'Define member Ranks',
                        path:  '/admin/member_ranks',
                        icon:  'angle-double-up' },
          roles:      { label: 'roles',
                        title: 'Member Roles',
                        desc:  'Define member Roles',
                        path:  '/admin/member_roles',
                        icon:  'shield' },
          attributes: { label: 'attributes',
                        title: 'Member Attributes',
                        desc:  'Define team-specific Attributes for your Members',
                        path:  '/admin/member_attributes',
                        icon:  'list' },
          # onboarding: { label: "onboarding",
          #               title: "Member Onboarding",
          #               desc:  "Configure new-member onboarding policy",
          #               path:  "/admin/member_onboarding",
          #               icon:  "child" },
          registry:   { label: 'registry',
                        title: 'Member Registry',
                        desc:  'Assign Ranks and Roles to your Members',
                        path:  '/admin/member_registry',
                        icon:  'group',
                        view:  'manager' },
          add:       {  label:  'add',
                        title: 'Add Member',
                        desc:  'Add new Member',
                        path:  '/admin/member_add',
                        icon:  'user-plus',
                        view:  'manager' },
          drop:       { label: 'drop',
                        title: 'Drop Member',
                        desc:  'Drop a Member',
                        path:  '/admin/member_drop',
                        icon:  'trash',
                        view:  'manager' },
      },
      Lica_Qualifications: {
        index:        { label: 'index',
                        title: 'Qualifications',
                        desc:  'Create/Update/Delete qualifications',
                        path:  '/admin/quals',
                        icon:  'database' },
        ctypes:        { label: 'types',
                         title: 'Certification Types',
                         desc:  'Create/Update/Delete cert types',
                         path:  '/admin/qual_ctypes',
                         icon:  'pencil-square-o' },
        assignments:  { label: 'assignments',
                        title: 'Qualification Assignments',
                        desc:  'Assign cert types to qualifications',
                        path:  '/admin/qual_assignments',
                        icon:  'check-square-o' },
        partners:     { label: "partners",
                        title: "Qualification Partners",
                        desc:  "Manage partner qualifications",
                        path:  "/admin/qual_partners",
                        icon:  "cogs" },
      },
      Lica_Events: {
        types:      { label: 'types',
                      title: 'Event Types',
                      desc:  'Define the Event Types for your Team',
                      path:  '/admin/event_types',
                      icon:  'table' },
        roles:      { label: 'roles',
                      title: 'Event Roles',
                      desc:  'Define the Event Roles for your Team',
                      path:  '/admin/event_roles',
                      icon:  'shield' },
        attributes: { label: "attributes",
                     title: "Event Attributes",
                     desc:  "Define team-specific Attributes for your Events",
                     path:  "/admin/event_attributes",
                     icon:  "list" },
      },
      Lica_Positions: {
        index:        { label: 'index',
                        title: 'Positions',
                        desc:  'Create/Update/Delete positions',
                        path:  '/admin/position_index',
                        icon:  'database' },
        partners:     { label: 'partners',
                        title: 'Position Partners',
                        desc:  'Manage partner positions',
                        path:  '/admin/position_partners',
                        icon:  'cogs' },
      },
      # Lica_Services: {
      #   index:        { label: 'index',
      #                   title: 'Service Index',
      #                   desc:  'Add and remove services',
      #                   path:  '/admin/svc_index',
      #                   icon:  'database' },
      #   reports:      { label: 'reports',
      #                   title: 'Service Reports',
      #                   desc:  'Create customized service reports',
      #                   path:  '/admin/svc_reps',
      #                   icon:  'bar-chart-o' },
      #   partners:     { label: 'partners',
      #                   title: 'Partner Services',
      #                   desc:  'Manage partner services',
      #                   path:  '/admin/svc_partners',
      #                   icon:  'cogs' },
      # },
      # Lica_Forums: {
      #   index:        { label: 'index',
      #                   title: 'Forum Index',
      #                   desc:  'Create, update and delete Forums',
      #                   path:  '/admin/forum_index',
      #                   icon:  'comments' },
      #   partners:     { label: 'partners',
      #                   title: 'Forum Partners',
      #                   desc:  'Manage partner forums',
      #                   path:  '/admin/forum_partners',
      #                   icon:  'cogs' },
      # },
      # Lica_Drives: {
      #   index:        { label: 'index',
      #                   title: 'Drive Index',
      #                   desc:  'Create, update and delete Drives',
      #                   path:  '/admin/drive_index',
      #                   icon:  'database' },
      #   partners:     { label: 'partners',
      #                   title: 'Drive Partners',
      #                   desc:  'Manage partner drives',
      #                   path:  '/admin/drive_partners',
      #                   icon:  'cogs' },
      # },
      # Lica_Wikis: {
      #   index:        { label: 'index',
      #                   title: 'Wiki Index',
      #                   desc:  'Create, update and delete Wikis',
      #                   path:  '/admin/wiki_index',
      #                   icon:  'database' },
      #   partners:     { label: 'partners',
      #                   title: 'Wiki Partners',
      #                   desc:  'Manage partner wikis',
      #                   path:  '/admin/wiki_partners',
      #                   icon:  'cogs' },
      # },
  }

  def self.menus
    MENUS
  end

end