class Pgr::Action::StiOpReturnHome < Pgr::Action

  # ----- attributes -----
  xfield_accessor :period_id

  # ----- associations -----
  belongs_to :period, class_name: 'Event::Period'

  # ----- validation -----
  validates :period_id, presence: true

  # ----- class methods -----

  def self.about
    <<-EOF.gsub('      ','').gsub("\n", ' ')
      The Returned-Home action asks the page recipient
      to reply upon returning home for an event.  Returned-Home
      messages are associated with a single operational
      period.  When someone replies, the time is recorded,
      and they are designated as being at home.
    EOF
  end

  def self.usage_ctxt
    'People are returning home for an event'
  end

  def self.has_period; true; end;

  def self.label
    'Returned Home'
  end

  # ----- instance methods (page display) -----
  def label
    self.class.label
  end

  def status_msg
    'TBD'
  end

  # ----- instance methods -----

  def email_footer_html
    'Email Action Footer - Generated by StiOpReturnHome#email_footer_html'
  end

  def email_footer_text
    'Email Action Footer - Generated by StiOpReturnHome#email_footer_text'
  end

  def sms_footer
    'SMS Action Footer - Generated by StiOpReturnHome#sms_footer'
  end
end

# == Schema Information
#
# Table name: pgr_actions
#
#  id               :integer          not null, primary key
#  pgr_broadcast_id :integer
#  type             :string
#  xfields          :hstore           default({})
#  created_at       :datetime
#  updated_at       :datetime
#
