#!/usr/bin/env bash
# should be called from tmux_console

export APP="LICA-DEV"

sendkeys() {
  tmux send-keys -t $APP:$1 "$2" C-m
}

splitwin() {
  tmux split-window -v -p $1 -t $APP:$2
}

create_new_session()
{

  tmux new-session -s $APP -n "TEST" -d

  splitwin 50 1

  sendkeys 1.1 'script/run/specs'  
  sendkeys 1.2 'jest --watch'     

  # ----- -----

  tmux new-window -n "SERVER"

  sendkeys 2.1 'script/run/server' 

  # ----- -----

  tmux new-window -n "WEBPACK"

  sendkeys 3.1 'clear ; webpack-dev-server --host 0.0.0.0 --public soak:8080'

  # ----- -----

  tmux new-window -n "SIDEKIQ"

  sendkeys 4.1 'script/run/sidekiq'

  # ----- -----

  tmux new-window -n "TUNNEL"

  splitwin 70 4

  sendkeys 5.1 'clear ; rpf deploy@x440h64:3000 3000'

  # ----- -----

  tmux select-window -t $APP:1

}
