#!/usr/bin/env bash
# should be called from tmux_console

export APP="LICA-DEV"

create_new_session()
{

  # ----- DEV Window -----

  tmux new-session -s $APP -n "DEV" -d

  tmux split-window -v -t $APP:1      # horizontal split

  tmux send-keys -t $APP:1.1 'script/run/specs'  C-m # spec runner
  tmux send-keys -t $APP:1.2 'script/run/server' C-m # app server

  # ----- JOBS Window -----

  tmux new-window -n "JOBS"

  tmux split-window -v -p 50 -t $APP:2   # horizontal split 

  tmux send-keys -t $APP:2.1 'clear ; bundle exec sidekiq -C config/sidekiq.yml' C-m # bg jobs

  # ----- Webpacker Window -----

  tmux new-window -n "WEBPACK"

  tmux split-window -v -p 50 -t $APP:3   # horizontal split

  tmux send-keys -t $APP:3.1 'clear ; webpack-dev-server --host 0.0.0.0' C-m # webpack development server

  # ----- Tunnel Window -----

  tmux new-window -n "TUNNEL"

  tmux split-window -v -p 70 -t $APP:4   # horizontal split

  tmux send-keys -t $APP:4.1 'clear ; rpf deploy@Licah64:3000 3000'  C-m     # for inbound email testing

  # ----- Open With DEV Window -----

  tmux select-window -t $APP:1

}
